name: aggr
description:  dart port of Agg a Rust port of Anti-Grain Geometry
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  path: any
  image: any
  excel: 3.0.0
  http: any
  crypto: any

  ffi: any
  native_synchronization: any
  shared_map: ^1.1.6


dev_dependencies:
  pedantic: ^1.10.0
  test: any
